/// Flutter icons SuperListApp
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SuperListApp
///      fonts:
///       - asset: fonts/SuperListApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SuperListApp {
  SuperListApp._();

  static const _kFontFam = 'SuperListApp';
  static const String? _kFontPkg = null;

  static const IconData notification_app = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_app = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_app = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData task_app = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
